In [1]:
# installation guide for ROOT: https://www.nbi.dk/~petersen/Teaching/Stat2014/installation_python_root.html

# Make all the settings: This script must always be run at the beginning

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"  # Or 2, 3, etc. other than 0
import sys
import h5py
import numpy as np
import math
import time
import glob
import keras
import argparse
import keras.backend as K
from tf_AnalysisUtils import *
import tensorflow as tf
print(tf.__version__)
import pickle

if 'tlab' in os.environ.get('HOSTNAME'): # Here a check for host can be used
    tlab = True
else:
    tlab= False

sys.path.insert(1, os.path.join(sys.path[0], '..'))


#Architectures 
from PTF_models_v2 import generator, discriminator

dformat = 'channels_first'  #last
latent = 200
K.set_image_data_format(dformat)# setting global flag   
datapath = "/eos/home-f/frehm/TF2/Data/EleEscan_1_1/EleEscan_1_1.h5" # Training data CERN EOS                                                                                                                          
#dweights = ["/eos/home-f/frehm/TF2/Skripts/F02-03/pure tf/PTF_runs/PTF_11/PTF_11_1/Weights/disc/disc_weights_80.p"]
#gweights = ["/eos/home-f/frehm/TF2/Skripts/F02-03/pure tf/PTF_runs/PTF_11/PTF_11_1/Weights/gen/gen_weights_80.p"]
dweights = ["disc_weights_87.p"]
gweights = ["gen_weights_87.p"]
#save_path = "/eos/home-f/frehm/TF2/Skripts/F02-03/pure tf/PTF_runs/PTF_11/"
save_path = "/eos/home-f/frehm/TF2/Skripts/F02-03/pure tf/PTF up to date files/PTF Analysis Scripts Plots/"
#save_folder_name = "PTF_13"
save_folder_name = ""
energies = [0, 50, 100, 200, 250, 300, 400, 500]
sortdir = 'SortedData'
gendir = '/Weights/gen'
discdir = '/Weights/disc'
binevents = 100000 #100000
nbEvents = 2000
moments = 3
xscales = [1]
thresh = 0
particle = "Ele"
labels=['']
from Functions_v1 import *
save_path = save_path + save_folder_name
create_folder(save_path+ "/validation")
create_folder(save_path+ "/validation/plots")
plotsdir = save_path + "/validation/plots/"
ifpdf = True
stest = False
cell = 0


Using TensorFlow backend.


1.14.0
Directory  /eos/home-f/frehm/TF2/Skripts/F02-03/pure tf/PTF up to date files/PTF Analysis Scripts Plots//validation  already exists
Directory  /eos/home-f/frehm/TF2/Skripts/F02-03/pure tf/PTF up to date files/PTF Analysis Scripts Plots//validation/plots  already exists


In [ ]:
error

# Create the validation Data. For this script is TF2 needed and no PyROOT

In [2]:
var= perform_calculations_multi(generator, discriminator, gweights, dweights, energies, datapath, sortdir, gendir, discdir, num_data=nbEvents
     , num_events=binevents, m=moments, scales=xscales, thresh=thresh, latent=latent, particle=particle, dformat=dformat)

1
Searching in : /eos/home-f/frehm/TF2/Data/EleEscan_1_1/EleEscan_1_1.h5
Found 1 files. 
1
0
['/eos/home-f/frehm/TF2/Data/EleEscan_1_1/EleEscan_1_1.h5']
Loading Data from ..... /eos/home-f/frehm/TF2/Data/EleEscan_1_1/EleEscan_1_1.h5
2000 events were loaded in 9.95914626121521 seconds
11309 events were put in 8 bins
Actual Data
Energy	Events	Maximum Value			Maximum loc	Mean		Momentx2	Momenty2	Momentz2
0	9999	0.3791		[11.97239724 12.00040004 11.97559756]	0.00		2.6556		2.1207		20.6223
50	166	0.0623		[11.92771084 11.9939759   9.76506024]	0.00		3.1588		2.1814		21.2618
100	187	0.1086		[11.97860963 11.99465241 11.05347594]	0.00		2.6459		2.1748		21.0625
200	190	0.1790		[11.87894737 12.         11.42631579]	0.00		2.5111		2.1095		20.8196
250	205	0.2431		[12.         12.         12.09268293]	0.00		2.3630		2.1087		20.2026
300	198	0.3006		[11.98989899 11.99494949 12.58585859]	0.00		2.3476		2.1095		20.4687
400	185	0.3535		[12.         12.00540541 13.        ]	0.00		2.3549		2.0981		20.0070
500	179	0.

disc_out shape:  (3, 9999, 1)
Discriminator took 77.1037769317627 seconds for 9999 data and generated events
Calculations for .... 0
len_labels:  166
gen_images:  (166, 1, 25, 25, 25)
Generator took 0.8256981372833252 seconds to generate 166 events
len images:  166
disc_out:  (<tf.Tensor: id=103776, shape=(50, 1), dtype=float32, numpy=
array([[0.20911717],
       [0.6848041 ],
       [0.3763525 ],
       [0.588823  ],
       [0.21468845],
       [0.34320176],
       [0.30966133],
       [0.3359788 ],
       [0.5135404 ],
       [0.23036963],
       [0.48224515],
       [0.08380398],
       [0.3946328 ],
       [0.2162529 ],
       [0.7643214 ],
       [0.39825076],
       [0.28655815],
       [0.32361662],
       [0.11642766],
       [0.30081928],
       [0.5391573 ],
       [0.76441765],
       [0.1271002 ],
       [0.4926196 ],
       [0.20748821],
       [0.82008874],
       [0.28627473],
       [0.49031103],
       [0.39653927],
       [0.6127068 ],
       [0.9334739 ],
       [0.1

disc_out shape:  (3, 166, 1)
Discriminator took 1.6361193656921387 seconds for 166 data and generated events
Calculations for .... 50
len_labels:  187
gen_images:  (187, 1, 25, 25, 25)
Generator took 1.4446756839752197 seconds to generate 187 events
len images:  187
disc_out:  (<tf.Tensor: id=105880, shape=(50, 1), dtype=float32, numpy=
array([[0.5954248 ],
       [0.27401593],
       [0.6273031 ],
       [0.3028866 ],
       [0.44641164],
       [0.217789  ],
       [0.34492737],
       [0.42005002],
       [0.62563187],
       [0.40582687],
       [0.29834583],
       [0.28669685],
       [0.28199238],
       [0.6652672 ],
       [0.35381144],
       [0.22412837],
       [0.59437513],
       [0.3408888 ],
       [0.48808342],
       [0.41715008],
       [0.43606263],
       [0.3878263 ],
       [0.6520619 ],
       [0.3886103 ],
       [0.9682912 ],
       [0.12273118],
       [0.37104094],
       [0.85807455],
       [0.40799043],
       [0.46640438],
       [0.52635986],
       [0.

disc_out shape:  (3, 187, 1)
Discriminator took 2.1921088695526123 seconds for 187 data and generated events
Calculations for .... 100
len_labels:  190
gen_images:  (190, 1, 25, 25, 25)
Generator took 1.532329797744751 seconds to generate 190 events
len images:  190
disc_out:  (<tf.Tensor: id=107984, shape=(50, 1), dtype=float32, numpy=
array([[0.61264   ],
       [0.34298965],
       [0.3517977 ],
       [0.27235186],
       [0.54973143],
       [0.36535388],
       [0.7273512 ],
       [0.61251646],
       [0.8436711 ],
       [0.5605361 ],
       [0.41519848],
       [0.15432799],
       [0.24258089],
       [0.40671146],
       [0.40837002],
       [0.6153656 ],
       [0.4534638 ],
       [0.34710294],
       [0.26481533],
       [0.22871715],
       [0.30709425],
       [0.34205675],
       [0.20645478],
       [0.6004205 ],
       [0.4577186 ],
       [0.25052947],
       [0.7370901 ],
       [0.17193836],
       [0.41632134],
       [0.6191141 ],
       [0.23137134],
       [0.

disc_out shape:  (3, 190, 1)
Discriminator took 2.2671117782592773 seconds for 190 data and generated events
Calculations for .... 200
len_labels:  205
gen_images:  (205, 1, 25, 25, 25)
Generator took 0.669527530670166 seconds to generate 205 events
len images:  205
disc_out:  (<tf.Tensor: id=110186, shape=(50, 1), dtype=float32, numpy=
array([[0.45218575],
       [0.27575296],
       [0.81154734],
       [0.4916739 ],
       [0.42544693],
       [0.39231092],
       [0.7930769 ],
       [0.60844487],
       [0.4191359 ],
       [0.35967374],
       [0.6363342 ],
       [0.44185328],
       [0.43633133],
       [0.41225082],
       [0.48724565],
       [0.34847242],
       [0.24837527],
       [0.3685375 ],
       [0.24260587],
       [0.5693792 ],
       [0.47443166],
       [0.33739597],
       [0.23616657],
       [0.5519221 ],
       [0.38121122],
       [0.5345702 ],
       [0.44520295],
       [0.41132146],
       [0.34320426],
       [0.39967936],
       [0.4347781 ],
       [0.

disc_out shape:  (3, 205, 1)
Discriminator took 1.7110893726348877 seconds for 205 data and generated events
Calculations for .... 250
len_labels:  198
gen_images:  (198, 1, 25, 25, 25)
Generator took 1.7489805221557617 seconds to generate 198 events
len images:  198
disc_out:  (<tf.Tensor: id=112707, shape=(50, 1), dtype=float32, numpy=
array([[0.3234284 ],
       [0.36931908],
       [0.35475263],
       [0.35243833],
       [0.56250846],
       [0.4517334 ],
       [0.67142165],
       [0.3498274 ],
       [0.46319243],
       [0.60051835],
       [0.2841987 ],
       [0.27077454],
       [0.30007055],
       [0.5567691 ],
       [0.4556993 ],
       [0.6341163 ],
       [0.33298507],
       [0.46665215],
       [0.4931659 ],
       [0.23530734],
       [0.27777034],
       [0.6118962 ],
       [0.41156262],
       [0.46433884],
       [0.41217342],
       [0.7529257 ],
       [0.6017963 ],
       [0.55207604],
       [0.30529845],
       [0.54970133],
       [0.46460894],
       [0

disc_out shape:  (3, 198, 1)
Discriminator took 2.4644646644592285 seconds for 198 data and generated events
Calculations for .... 300
len_labels:  185
gen_images:  (185, 1, 25, 25, 25)
Generator took 1.396573543548584 seconds to generate 185 events
len images:  185
disc_out:  (<tf.Tensor: id=114811, shape=(50, 1), dtype=float32, numpy=
array([[0.32832313],
       [0.36940634],
       [0.25258338],
       [0.30718878],
       [0.45887837],
       [0.2369878 ],
       [0.3218679 ],
       [0.3153445 ],
       [0.5329024 ],
       [0.6643944 ],
       [0.29952633],
       [0.37264636],
       [0.41797373],
       [0.25561672],
       [0.3307526 ],
       [0.364188  ],
       [0.34242108],
       [0.56366074],
       [0.5930673 ],
       [0.35955977],
       [0.57067364],
       [0.3387977 ],
       [0.37408936],
       [0.32891628],
       [0.29924768],
       [0.55543256],
       [0.78874105],
       [0.30075228],
       [0.5743584 ],
       [0.5607174 ],
       [0.48933133],
       [0.

disc_out shape:  (3, 185, 1)
Discriminator took 2.156719923019409 seconds for 185 data and generated events
Calculations for .... 400
len_labels:  179
gen_images:  (179, 1, 25, 25, 25)
Generator took 1.2186613082885742 seconds to generate 179 events
len images:  179
disc_out:  (<tf.Tensor: id=116915, shape=(50, 1), dtype=float32, numpy=
array([[0.6842011 ],
       [0.43537635],
       [0.37046444],
       [0.3974734 ],
       [0.50254786],
       [0.38142055],
       [0.26010406],
       [0.47849405],
       [0.32268244],
       [0.28863853],
       [0.32162994],
       [0.2715162 ],
       [0.35631213],
       [0.32997674],
       [0.4779395 ],
       [0.2849921 ],
       [0.34718046],
       [0.31437856],
       [0.50431585],
       [0.5294848 ],
       [0.23682079],
       [0.3875686 ],
       [0.46277124],
       [0.40734005],
       [0.41249   ],
       [0.5575506 ],
       [0.43601063],
       [0.46992084],
       [0.3885641 ],
       [0.18404955],
       [0.41313457],
       [0.

disc_out shape:  (3, 179, 1)
Discriminator took 1.9713950157165527 seconds for 179 data and generated events
Calculations for .... 500
Generated Data
Energy	Events	Maximum Value			Maximum loc			Mean		Momentx2	Momenty2	Momentz2
0	9999	0.9304		[21.54815482  6.98709871 15.47644764]			0.00		-1186.6309		-30525.5680		-117329.8273
50	166	0.4866		[21.07228916  9.         13.80120482]			0.00		-474.7949		-692.1608		-108.8736
100	187	0.6450		[21.20855615  9.20855615 14.07486631]			0.00		-31.8107		14.3701		-69.1648
200	190	0.5048		[20.93684211  8.4        13.86842105]			0.00		-33.2246		22.4864		-0.3958
250	205	0.5390		[20.89756098  8.98536585 13.55609756]			0.00		17.3760		23.5418		17.2277
300	198	0.8856		[20.81818182  8.78787879 13.60606061]			0.00		-132.9345		-7273.2883		-22463.8278
400	185	0.5069		[20.3027027   8.20540541 14.15135135]			0.00		8.1513		-20.9566		-28.6393
500	179	0.5484		[21.21787709  8.61452514 13.73184358]			0.00		-24.4233		38.2913		2.3188


In [3]:
pickle.dump(var, open( save_folder_name + "validation/plots/"+ "saved_var.p", "wb"))

In [ ]:
error

# Validation with PyROOT

### You have to run the code below in an environment which has PyROOT installed. Tensorflow is not needed anymore 

In [2]:
import ROOT
from tf_PlotsGANAnalysis import *

Welcome to JupyROOT 6.20/04


In [3]:
var_loaded = pickle.load( open( save_folder_name + "validation/plots/"+ "saved_var.p", "rb") )

In [4]:
def get_plots_multi(var, labels, plots_dir, energies, m, n, ifpdf=True, stest=True, cell=0, corr=0):

    actdir = plots_dir + 'Actual'
    safe_mkdir(actdir)
    discdir = plots_dir + 'disc_outputs'
    safe_mkdir(discdir)
    gendir = plots_dir + 'Generated'
    safe_mkdir(gendir)
    comdir = plots_dir + 'Combined'
    safe_mkdir(comdir)
    mdir = plots_dir + 'Moments'
    safe_mkdir(mdir)
    start = time.time()
    plots = 0
    ang = 0 # there is no angle data                                                                                                                                                                                                                                                      
    for energy in energies:
       x=var["events_act" + str(energy)].shape[1]
       y=var["events_act" + str(energy)].shape[2]
       z=var["events_act" + str(energy)].shape[3]
       maxfile = "Position_of_max_" + str(energy)# + ".pdf"                                                                                                                                                                                                                   
       maxlfile = "Position_of_max_" + str(energy)# + "_log.pdf"                                                                                                                                                                                                                          
       histfile = "hist_" + str(energy)# + ".pdf"                                                                                                                                                                                                                                         
       histlfile = "hist_log" + str(energy)# + ".pdf"                                                                                                                                                                                                                                     
       ecalfile = "ecal_" + str(energy)# + ".pdf"                                                                                                                                                                                                                                         
       energyfile = "energy_" + str(energy)# + ".pdf"                                                                                                                                                                                                                                     
       realfile = "realfake_" + str(energy)# + ".pdf"                                                                                                                                                                                                                                     
       momentfile = "moment" + str(energy)# + ".pdf"                                                                                                                                                                                                                                      
       auxfile = "Auxilliary_"+ str(energy)# + ".pdf"                                                                                                                                                                                                                                     
       ecalerrorfile = "ecal_error" + str(energy)# + ".pdf"                                                                                                                                                                                                                               
       allfile = 'All_energies'#.pdf'                                                                                                                                                                                                                                                     
       allecalfile = 'All_ecal'#.pdf'                                                                                                                                                                                                                                                     
       allecalrelativefile = 'All_ecal_relative'#.pdf'                                                                                                                                                                                                                                    
       allauxrelativefile = 'All_aux_relative'#.pdf'                                                                                                                                                                                                                                      
       allerrorfile = 'All_relative_auxerror'#.pdf'                                                                                                                                                                                                                                       
       correlationfile = 'Corr'
       start = time.time()
       if energy==0:
          plot_ecal_ratio_profile(var["ecal_act" + str(energy)], var["ecal_gan" + str(energy)], var["energy" + str(energy)], labels, os.path.join(comdir, allecalfile), ang=ang, stest=stest)
          plots+=1
          plot_aux_relative_profile(var["aux_act" + str(energy)], var["aux_gan"+ str(energy)], var["energy"+ str(energy)], os.path.join(comdir, allauxrelativefile), labels)
          plots+=1
          if corr==1:
             plot_correlation(var["sumsx_act"+ str(energy)], var["sumsy_act"+ str(energy)], var["sumsz_act"+ str(energy)], var["momentX_act" + str(energy)], var["momentY_act" + str(energy)], var["momentZ_act" + str(energy)], var["ecal_act" + str(energy)],  var["sumsx_gan"+ str(energy)], var["sumsy_gan"+ str(energy)], var["sumsz_gan"+ str(energy)], var["momentX_gan" + str(energy)], var["momentY_gan" + str(energy)], var["momentZ_gan" + str(energy)], var["ecal_gan" + str(energy)], var["energy" + str(energy)], var["events_act" + str(energy)], var["events_gan" + str(energy)], os.path.join(comdir, correlationfile), labels)
             plots+=1
          elif corr==2:
             plot_correlation_small(var["momentX_act" + str(energy)], var["momentY_act" + str(energy)], var["momentZ_act" + str(energy)], var["ecal_act" + str(energy)],  var["momentX_gan" + str(energy)], var["momentY_gan" + str(energy)], var["momentZ_gan" + str(energy)], var["ecal_gan" + str(energy)], var["energy" + str(energy)], var["events_act" + str(energy)], var["events_gan" + str(energy)], os.path.join(comdir, correlationfile+ "small"), labels)
             plots+=1
                                                                              
          if cell:
             plot_ecal_flatten_hist(var["events_act" + str(energy)], var["events_gan" + str(energy)], os.path.join(comdir, 'flat' + ecalfile), energy, labels, ang=ang)
             plots+=1
             plot_ecal_flatten_hist(var["events_act" + str(energy)], var["events_gan" + str(energy)], os.path.join(comdir, 'flat' + ecalfile), energy, labels, log=1, ang=ang)
             plots+=1
       plot_ecal_hist(var["ecal_act" + str(energy)], var["ecal_gan" + str(energy)], os.path.join(discdir, ecalfile), energy, labels, stest=stest, ang=ang)
       plots+=1
       if cell>1:
          plot_ecal_flatten_hist(var["events_act" + str(energy)], var["events_gan" + str(energy)], os.path.join(comdir, 'flat' + ecalfile), energy, labels, ang=ang)
          plots+=1
          plot_ecal_flatten_hist(var["events_act" + str(energy)], var["events_gan" + str(energy)], os.path.join(comdir, 'flat' + ecalfile), energy, labels, ang=ang)
          plots+=1
                    
       plot_ecal_hits_hist(var["events_act" + str(energy)], var["events_gan" + str(energy)], os.path.join(comdir, 'hits' + ecalfile), energy, labels, ang=ang)
       plots+=1
       plot_aux_hist(var["aux_act" + str(energy)], var["aux_gan" + str(energy)] , os.path.join(discdir, energyfile), energy, labels)
       plots+=1
       plot_max(var["max_pos_act" + str(energy)], var["max_pos_gan" + str(energy)], x, y, z, os.path.join(actdir, maxfile), os.path.join(gendir, maxfile), os.path.join(comdir, maxfile), energy, labels, stest=stest)
       plots+=1
       plot_max(var["max_pos_act" + str(energy)], var["max_pos_gan" + str(energy)], x, y, z, os.path.join(actdir, maxlfile), os.path.join(gendir, maxlfile), os.path.join(comdir, 'log' + maxlfile), energy, labels, log=1, stest=stest)
       plots+=1
       plot_energy_hist_root(var["sumsx_act"+ str(energy)], var["sumsy_act"+ str(energy)], var["sumsz_act"+ str(energy)], var["sumsx_gan"+ str(energy)], var["sumsy_gan"+ str(energy)], var["sumsz_gan"+ str(energy)], x, y, z, os.path.join(actdir, histfile), os.path.join(gendir,histfile), os.path.join(comdir, histfile), energy, labels, stest=stest)
       plots+=1
       plot_energy_hist_root(var["sumsx_act"+ str(energy)], var["sumsy_act"+ str(energy)], var["sumsz_act"+ str(energy)], var["sumsx_gan"+ str(energy)], var["sumsy_gan"+ str(energy)], var["sumsz_gan"+ str(energy)], x, y, z, os.path.join(actdir, histlfile), os.path.join(gendir, histlfile), os.path.join(comdir, histlfile), energy, labels, log=1, stest=stest)
       plots+=1
       plot_realfake_hist(var["isreal_act" + str(energy)], var["isreal_gan" + str(energy)], os.path.join(discdir, realfile), energy, labels)
       plots+=1
       plot_primary_error_hist(var["aux_act" + str(energy)], var["aux_gan" + str(energy)], var["energy" + str(energy)], os.path.join(discdir, 'error_' + energyfile), energy, labels)
       plots+=1
       for mmt in range(m):
          plot_moment(var["momentX_act" + str(energy)], var["momentX_gan" + str(energy)], os.path.join(mdir, 'x' + str(mmt + 1) + momentfile), 'x', energy, mmt, labels)
          plots+=1
          plot_moment(var["momentY_act" + str(energy)], var["momentY_gan" + str(energy)], os.path.join(mdir, 'y' + str(mmt + 1) + momentfile), 'y', energy, mmt, labels)
          plots+=1
          plot_moment(var["momentZ_act" + str(energy)], var["momentZ_gan" + str(energy)], os.path.join(mdir, 'z' + str(mmt + 1) + momentfile), 'z', energy, mmt, labels)
          plots+=1

    print('Plots are saved in ', plots_dir)
    plot_time= time.time()- start
    print('{} Plots are generated in {} seconds'.format(plots, plot_time))


In [5]:
get_plots_multi(var_loaded, labels, plotsdir, energies, moments, len(gweights), ifpdf, stest, cell)

Plots are saved in  /eos/home-f/frehm/TF2/Skripts/F02-03/pure tf/PTF up to date files/PTF Analysis Scripts Plots//validation/plots/
146 Plots are generated in 1.1562881469726562 seconds


Info in <TCanvas::Print>: pdf file /eos/home-f/frehm/TF2/Skripts/F02-03/pure tf/PTF up to date files/PTF Analysis Scripts Plots//validation/plots/Combined/All_ecal.pdf has been created
Info in <TCanvas::Print>: pdf file /eos/home-f/frehm/TF2/Skripts/F02-03/pure tf/PTF up to date files/PTF Analysis Scripts Plots//validation/plots/Combined/All_aux_relative.pdf has been created
Info in <TCanvas::Print>: pdf file /eos/home-f/frehm/TF2/Skripts/F02-03/pure tf/PTF up to date files/PTF Analysis Scripts Plots//validation/plots/disc_outputs/ecal_0.pdf has been created
Info in <TCanvas::Print>: pdf file /eos/home-f/frehm/TF2/Skripts/F02-03/pure tf/PTF up to date files/PTF Analysis Scripts Plots//validation/plots/Combined/hitsecal_0.pdf has been created
Info in <TCanvas::Print>: pdf file /eos/home-f/frehm/TF2/Skripts/F02-03/pure tf/PTF up to date files/PTF Analysis Scripts Plots//validation/plots/disc_outputs/energy_0.pdf has been created
Info in <TCanvas::Print>: pdf file /eos/home-f/frehm/TF2/Sk

In [6]:
print("Finished")

Finished
